# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Libre'), ('2', 'Reservado'), ('3', 'Pagado')], default='1', max_length=30)),
                ('resultado', models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze')], default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_jugada', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Abierto'), ('0', 'Cerrado'), ('-1', 'Pre-Cerrado')], default='1', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('sponsor_revenue', models.FloatField(null=True)),
                ('sponsor', models.ForeignKey(default='rafael', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='spn', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='jugada',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jugada',
            name='pote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betcnow.Pote'),
        ),
    ]
