# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sponsor_revenue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
