# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0002_auto_20170213_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sponsor',
            field=models.ForeignKey(default='betcnow', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='spn', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
