# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0004_auto_20170216_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugada',
            name='orderID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
