# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0005_jugada_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_membresia', models.CharField(choices=[('2', 'Member'), ('1', 'Free'), ('3', 'VIP')], default='1', max_length=30, unique=True)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='miembro_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='membresia',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='betcnow.Membership', to_field='tipo_membresia'),
        ),
    ]
