# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0008_auto_20170222_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='tipo_membresia',
            field=models.CharField(default='Free', max_length=30, unique=True),
        ),
    ]
