# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0010_auto_20170222_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='membresia',
            field=models.ForeignKey(default='Free', on_delete=django.db.models.deletion.CASCADE, to='betcnow.Membership', to_field='tipo_membresia'),
        ),
    ]
