# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0013_auto_20170223_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
