# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0016_jugada_fecha_jugada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sponsor_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
