# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0018_membership_porcentaje_jugada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='porcentaje_jugada',
            field=models.FloatField(max_length=10),
        ),
    ]
