# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0019_auto_20170302_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugada',
            name='resultado',
            field=models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze'), ('R', 'Repechage')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='porcentaje_jugada',
            field=models.FloatField(),
        ),
    ]
