# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0020_auto_20170302_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='pote',
            name='fecha_sorteo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
