# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0022_profile_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugada',
            name='premio',
            field=models.CharField(blank=True, choices=[('1', '300pts'), ('2', '25pts'), ('3', '20pts'), ('4', '0.001Btc+10pts')], default='', max_length=30),
        ),
    ]
