# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0025_auto_20170315_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='pote',
            name='total_acumulado',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
