# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0027_auto_20170321_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pote',
            name='total_acumulado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
