# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0029_sponsorsporpote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pote',
            name='bronze',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pote',
            name='copper',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pote',
            name='gold',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pote',
            name='primero',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pote',
            name='segundo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pote',
            name='silver',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pote',
            name='tercero',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
