# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-23 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0033_ipsycookies_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugada',
            name='premio',
            field=models.CharField(blank=True, choices=[('1', '160 Bitcoin Race points'), ('2', '40 Bitcoin Race points'), ('3', '20 Bitcoin Race points'), ('4', '10 Bitcoin Race points')], default='', max_length=30),
        ),
    ]
