# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0035_auto_20171023_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('status', models.CharField(choices=[('0', 'Disponible'), ('1', 'Canjeado')], default='0', max_length=30)),
            ],
        ),
    ]
