# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0036_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='codigo',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
