# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcnow', '0037_auto_20171024_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premio',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
